The `npm install` command failed in my project. Analyze the following error output and fix it, potentially involving changes to `package.json`.
NPM Error Output:
```
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
Error: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
[1;91merror[0m: [1mError validating field `hangar` in model `Alert`: The relation field `hangar` on model `Alert` is missing an opposite relation field on the model `Hangar`. Either run `prisma format` or add it manually.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:117[0m
[1;94m   | [0m
[1;94m116 | [0m  hangarId                BigInt?
[1;94m117 | [0m  [1;91mhangar                  Hangar?       @relation(fields: [hangarId], references: [id])[0m
[1;94m118 | [0m
[1;94m   | [0m

Validation Error Count: 1
[Context: getDmmf]

Prisma CLI Version : 5.22.0
npm error code 1
npm error path /home/user/studio
npm error command failed
npm error command sh -c prisma generate
npm error A complete log of this run can be found in: /home/.npm/_logs/2025-05-26T10_53_56_767Z-debug-0.log

```